Repository cloudflare/wrangler-legacy, pull requests merged in 2019-10, with the labels that each got.

#752 list author as wrangler at cloudflare dot com
  src/main.rs
Labels: changelog - maintenance

#750 Refactor site.rs calls to KV API (re-use commands::kv module logic)
  src/commands/kv/bucket/upload.rs
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/site.rs
Labels: category - refactor, status - needs review

#747 Print subdomain if `name` arg not provided to `wrangler subdomain`
  src/commands/mod.rs
  src/commands/subdomain.rs
  src/main.rs
Labels: changelog - feature, status - needs review

#757 Use custom KV api client to support longer timeouts
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/upload.rs
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/site.rs
Labels: priority - nice to have, status - needs review

#760 [Wrangler Ignore option 2] exclude/include logic in wrangler.toml for static asset uploads
  Cargo.lock
  Cargo.toml
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/mod.rs
  src/settings/target/mod.rs
Labels: category - feature, priority - critical, status - needs review, subject - site

#751 Deprecate release
  docs/content/environments.md
  src/commands/init.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/mod.rs
  src/commands/publish/mod.rs
  src/main.rs
  src/settings/target/mod.rs
  src/settings/target/tests/mod.rs
  src/settings/target/tests/tomls/default.toml
  src/settings/target/tests/tomls/environments.toml
  src/settings/target/tests/tomls/invalid_environments.toml
  src/settings/target/tests/tomls/kv_namespaces.toml
  src/settings/target/tests/tomls/legacy/default.toml
  src/settings/target/tests/tomls/legacy/kv_namespaces.toml
  src/settings/target/tests/tomls/no_default.toml
Labels: changelog - BREAKING, changelog - maintenance, status - needs review

#764 Clean up subdomain creation
  src/commands/publish/mod.rs
  src/commands/subdomain.rs
Labels: changelog - maintenance, status - needs review

#785 clean up bucket test directories
  src/commands/kv/bucket/mod.rs
Labels: category - maintenance, priority - low, status - needs review

#792 prohibit upload of directory named node_modules
  src/commands/kv/bucket/mod.rs
Labels: priority - critical, status - needs review

#793 Fix some clippy warnings
  src/commands/build/wranglerjs/mod.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/mod.rs
  src/commands/kv/key/put.rs
  src/commands/publish/upload_form/mod.rs
  src/main.rs
  src/settings/target/mod.rs
  tests/config.rs
Labels: changelog - maintenance

#790 Verbose file printouts when using wrangler publish with a Worker Site
  src/commands/kv/bucket/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/preview/upload.rs
  src/main.rs
Labels: priority - critical

#789 Disallow templates with generate site
  src/main.rs
Labels: changelog - fix

#699 Fix Rust Live Preview
  src/commands/build/watch/mod.rs
Labels: priority - nice to have, status - needs review

#797 use cloudflare worker to proxy requests to github and cache distribution binaries
  npm/install-wrangler.js
  src/install/mod.rs
Labels: priority - critical, status - needs review

#795 feat(publish): better error msg on needs email verif
  src/commands/publish/mod.rs
Labels: category - feature

#804 Privado deprecado
  src/settings/target/manifest.rs
  src/settings/target/tests/tomls/invalid_environments.toml
  src/settings/target/tests/tomls/kv_namespaces.toml
  src/settings/target/tests/tomls/no_default.toml
Labels: changelog - BREAKING, changelog - feature

#806 Bump Workers KV upload limit check to 10MB + run size checks over actual file, not its base64 encoding
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
Labels: priority - critical, status - needs review

#759 Use template wrangler.toml when generating
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/mod.rs
  src/main.rs
  src/settings/target/environment.rs
  src/settings/target/manifest.rs
  src/settings/target/target_type.rs
Labels: changelog - feature, status - needs review

#810 Remove backwards compatibility section from environment docs
  docs/content/environments.md
Labels: category - docs

#801 👻 1.5.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/index.html
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release

#811 fix(installer): bump version
  npm/install-wrangler.js
Labels: changelog - fix

#817 Pull version from package.json
  npm/install-wrangler.js
Labels: changelog - maintenance

#813 Handle duplicate route error gracefully
  src/commands/publish/route.rs
Labels: changelog - feature

#823 Move docs from READMEs to real docs
  README.md
  docs/_installer/build-installer.rs
  docs/_installer/index.html
  docs/_installer/init.sh
  docs/_installer/wrangler.js
  docs/content/environments.md
  docs/content/kv_commands.md
  docs/content/webpack.md
  docs/index.html
  docs/site.webmanifest
  npm/README.md
  src/main.rs
Labels: status - work in progress

#829 Remove --version on subcommands
  src/main.rs
Labels: changelog - fix

#831 Put each subcommand in its own directory
  src/commands/config/mod.rs
  src/commands/generate/mod.rs
  src/commands/init/mod.rs
  src/commands/mod.rs
  src/commands/preview/fiddle_messenger.rs
  src/commands/preview/http_method.rs
  src/commands/preview/mod.rs
  src/commands/preview/upload.rs
  src/commands/publish/mod.rs
  src/commands/subdomain/mod.rs
  src/commands/whoami/mod.rs
Labels: changelog - refactor
