Repository cloudflare/wrangler-legacy, pull requests merged in 2019-08, with the labels that each got.

#383 Move test fixtures to their own directory
  tests/build.rs
  tests/fixtures/simple_js/index.js
  tests/fixtures/simple_js/package.json
  tests/fixtures/simple_rust/Cargo.toml
  tests/fixtures/simple_rust/src/lib.rs
  tests/fixtures/simple_rust/src/utils.rs
  tests/fixtures/simple_rust/worker/metadata_wasm.json
  tests/fixtures/simple_rust/worker/worker.js
  tests/fixtures/webpack_multiple_config/index.js
  tests/fixtures/webpack_multiple_config/package.json
  tests/fixtures/webpack_multiple_config/webpack.config.js
  tests/fixtures/webpack_multiple_specify_config/index.js
  tests/fixtures/webpack_multiple_specify_config/package.json
  tests/fixtures/webpack_multiple_specify_config/webpack.worker.js
  tests/fixtures/webpack_simple_js/index.js
  tests/fixtures/webpack_simple_js/package.json
  tests/fixtures/webpack_simple_js/webpack.config.js
  tests/fixtures/webpack_single_js_missing_package_main/index.js
  tests/fixtures/webpack_single_js_missing_package_main/package.json
  tests/fixtures/webpack_single_js_use_package_main/index.js
  tests/fixtures/webpack_single_js_use_package_main/package.json
  tests/fixtures/webpack_specify_config/index.js
  tests/fixtures/webpack_specify_config/package.json
  tests/fixtures/webpack_specify_config/webpack.worker.js
  tests/fixtures/webpack_wast/index.js
  tests/fixtures/webpack_wast/module.wast
  tests/fixtures/webpack_wast/package.json
  tests/fixtures/webpack_wast/webpack.config.js
  tests/preview.rs
Labels: changelog - maintenance, status - needs review

#391 refactor: move emoji formatting into concrete fns
  src/terminal/message.rs
Labels: category - refactor, changelog - feature

#394 Improve JSON errors debuggability
  src/commands/build/wranglerjs/mod.rs
  src/commands/publish/package.rs
  src/commands/publish/preview/mod.rs
Labels: changelog - feature, status - needs review

#387 Update issue templates to fit Github's data model
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: changelog - maintenance, status - needs review

#382 Migrate straggler emojis to terminal::emoji
  src/commands/publish/route.rs
  src/commands/subdomain.rs
  src/install/mod.rs
Labels: changelog - maintenance, status - needs review

#399 Fix `wrangler config` for systems with non-unix EOL
  src/commands/config.rs
  src/main.rs
  tests/config.rs
Labels: changelog - fix

#392 feat create namespace
  Cargo.lock
  Cargo.toml
  README.md
  docs/content/kv_commands.md
  src/commands/kv/create_namespace.rs
  src/commands/kv/mod.rs
  src/commands/mod.rs
  src/main.rs
  src/settings/global_user.rs
  src/terminal/emoji.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#408 refactor: handle success in endpoint caller
  src/commands/kv/create_namespace.rs
  src/commands/kv/mod.rs
Labels: subject - kv

#407 Add section to readme about Vendored OpenSSL
  README.md
Labels: changelog - docs

#403 feat: #348 rename namespace
  docs/content/kv_commands.md
  src/commands/kv/mod.rs
  src/commands/kv/rename_namespace.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#404 feat: #342 list namespaces
  docs/content/kv_commands.md
  src/commands/kv/list_namespaces.rs
  src/commands/kv/mod.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#414 Fix capitalization in README
  README.md
Labels: changelog - maintenance

#416 Add wrangler --version to bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: changelog - maintenance

#379 Update README to include config, env var changes
  README.md
  wrangler-demo.gif
Labels: changelog - docs

#419 feat(npm-installer): install current version, not latest
  npm/README.md
  npm/install-wrangler.js
Labels: changelog - feature

#420 Update npm installer version to 1.1.1
  npm/package.json
Labels: changelog - maintenance

#422 Link to docs for update instructions
  README.md
Labels: changelog - docs

#425 Add repository link to Cargo.toml
  Cargo.toml
Labels: changelog - maintenance

#432 Fix ignoring exit code from spawnSync - run-wrangler.js
  npm/run-wrangler.js
Labels: changelog - fix

#427 Nits: fix clippy warnings
  src/commands/publish/package.rs
  src/terminal/message.rs
Labels: changelog - maintenance

#443 Don't install cargo-generate in ci
  azure-pipelines.yml
Labels: changelog - maintenance

#440 Cleanup README and link to workers docs
  README.md
Labels: changelog - docs

#429 feat: authenticate calls to preview service when possible
  src/commands/publish/preview/mod.rs
  src/main.rs
  src/terminal/emoji.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#444 fix typo
  CONTRIBUTING.md
Labels: changelog - maintenance

#437 Update cloudflare-rs invocations to match updates
  Cargo.lock
  Cargo.toml
  src/commands/kv/create_namespace.rs
  src/commands/kv/delete_namespace.rs
  src/commands/kv/list_namespaces.rs
  src/commands/kv/mod.rs
  src/commands/kv/rename_namespace.rs
Labels: status - work in progress, subject - kv

#451 Xortive malonso/hotreload + windows ampersand escape fix
  Cargo.lock
  Cargo.toml
  src/commands/build/mod.rs
  src/commands/build/watch/mod.rs
  src/commands/build/watch/watcher.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/build/wranglerjs/output.rs
  src/commands/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/fiddle_messenger.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/preview/upload.rs
  src/main.rs
  src/util.rs
  wranglerjs/index.js
Labels: changelog - feature

#453 fix(installer): bump npm version
  npm/install-wrangler.js
Labels: changelog - fix

#454 Add gets for single keys from Workers KV
  Cargo.lock
  Cargo.toml
  src/commands/kv/mod.rs
  src/commands/kv/read_key.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#458 Add individual write subcommand for Workers KV
  Cargo.lock
  Cargo.toml
  src/commands/kv/mod.rs
  src/commands/kv/write_key.rs
  src/main.rs
Labels: changelog - feature, priority - critical, subject - kv

#445 Add bulk upload to Workers KV
  Cargo.lock
  Cargo.toml
  src/commands/kv/mod.rs
  src/commands/kv/write_bulk.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#455 Clean up emoji
  src/terminal/emoji.rs
Labels: changelog - maintenance, status - needs review

#452 Implementation of single and bulk deletion from KV
  src/commands/kv/delete_bulk.rs
  src/commands/kv/delete_key.rs
  src/commands/kv/mod.rs
  src/commands/kv/write_bulk.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#462 Add key listing functionality for workers kv subcommands
  Cargo.lock
  src/commands/kv/list_keys.rs
  src/commands/kv/mod.rs
  src/main.rs
Labels: category - feature, priority - critical, status - needs review, subject - kv

#485 Remove logic for uploading directories from bulk
  src/commands/kv/delete_bulk.rs
  src/commands/kv/mod.rs
  src/commands/kv/write_bulk.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#501 Gabbi/update subcommand invocations
  src/main.rs
Labels: priority - critical, status - needs review, subject - kv
