Repository cloudflare/wrangler-legacy, pull requests merged in 2019-06, with the labels that each got.

#191 fix: make sure to remove lock
  src/wranglerjs/mod.rs
Labels: needs review

#190 1.0.0
  Cargo.lock
  Cargo.toml
  README.md
  npm/package.json
Labels: release

#200 minor spelling
  src/commands/publish/route.rs
Labels: changelog - fix

#202 reorganize wranglerjs src
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/build/wranglerjs/output.rs
  src/commands/publish/mod.rs
  src/main.rs
  src/wranglerjs/mod.rs
Labels: changelog - maintenance

#205 feat: show sizes
  Cargo.lock
  Cargo.toml
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/output.rs
Labels: changelog - feature

#233 Display commands in their defined order
  src/emoji.rs
  src/main.rs
Labels: changelog - feature

#245 Enforce one webpack config
  tests/build.rs
  tests/webpack_multiple_config/package.json
  tests/webpack_multiple_config/webpack.config.js
  wranglerjs/index.js
Labels: changelog - feature

#260 fix: correct binding format
  src/commands/build/wranglerjs/bundle.rs
Labels: changelog - fix, webpack

#261 fix: correctly pass Wasm module
  Cargo.lock
  Cargo.toml
  src/commands/build/wranglerjs/bundle.rs
  wranglerjs/index.js
Labels: changelog - fix, webpack

#257 clarified intro link in README
  README.md
Labels: changelog - docs

#253 feat: allow custom webpack configuration in wrangler.toml
  README.md
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/mod.rs
  src/main.rs
  src/settings/project.rs
  tests/build.rs
  tests/webpack_multiple_config/index.js
  tests/webpack_multiple_specify_config/index.js
  tests/webpack_multiple_specify_config/package.json
  tests/webpack_multiple_specify_config/webpack.worker.js
  tests/webpack_specify_config/index.js
  tests/webpack_specify_config/package.json
  tests/webpack_specify_config/webpack.worker.js
  wranglerjs/index.js
Labels: changelog - feature

#263 Add message module for terminal output
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/bundle.rs
  src/commands/config.rs
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/subdomain.rs
  src/commands/whoami.rs
  src/main.rs
  src/terminal/emoji.rs
  src/terminal/message.rs
  src/terminal/mod.rs
Labels: changelog - feature

#259 feat: adds more descriptive subdomain errors
  src/commands/subdomain.rs
Labels: changelog - feature, status - changes requested
