Repository cloudflare/wrangler-legacy, pull requests merged in 2019-11, with the labels that each got.

#822 Match wasm binding name in webpack to rust default
  src/commands/build/wranglerjs/bundle.rs
Labels: changelog - fix, priority - low, subject - webpack

#830 Fix default value for wrangler generate template
  src/main.rs
Labels: changelog - fix

#832 Fix unused code warnings in tests
  tests/build.rs
  tests/preview.rs
Labels: changelog - maintenance

#471 Add API token support
  Cargo.lock
  Cargo.toml
  README.md
  src/commands/config/mod.rs
  src/commands/kv/mod.rs
  src/commands/preview/upload.rs
  src/commands/whoami/mod.rs
  src/http.rs
  src/main.rs
  src/settings/global_user.rs
  tests/config.rs
Labels: priority - critical, status - needs review

#836 Update author of npm package to wrangler@
  npm/package.json
Labels: changelog - maintenance

#835 Introduce enum for GlobalUser to handle distinct authentication methods (token vs global api key)
  src/commands/whoami/mod.rs
  src/http.rs
  src/main.rs
  src/settings/global_user.rs
Labels: changelog - maintenance, status - needs review

#837 Add help suggestion on webpack failure
  src/commands/build/wranglerjs/mod.rs
Labels: changelog - feature, status - needs review, subject - webpack

#838 Fix link in readme
  README.md
Labels: category - docs, status - needs review

#816 Add the ability to preview without opening the browser
  src/commands/preview/mod.rs
  src/main.rs
  tests/preview.rs
Labels: changelog - feature, status - needs review

#846 Audit comments
  CONTRIBUTING.md
  npm/install-wrangler.js
  src/commands/build/watch/mod.rs
  src/commands/build/watch/watcher.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/build/wranglerjs/output.rs
  src/commands/config/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/put.rs
  src/commands/mod.rs
  src/commands/preview/fiddle_messenger.rs
  src/commands/preview/mod.rs
  src/commands/publish/upload_form/mod.rs
  src/main.rs
  src/settings/target/manifest.rs
  src/settings/target/site.rs
  src/settings/target/target.rs
  src/util.rs
  wranglerjs/index.js
Labels: changelog - maintenance

#853 Clean up wranglerjs temp file
  src/commands/build/wranglerjs/mod.rs
Labels: changelog - fix, status - needs review

#841 Refactor cloudflare-rs cli to be called from http.rs
  src/commands/kv/mod.rs
  src/http.rs
Labels: category - refactor, priority - critical, status - work in progress

#851 add scaffold_worker method to Site, use all the PathBufs
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate/mod.rs
  src/commands/init/mod.rs
  src/commands/kv/bucket/mod.rs
  src/commands/publish/mod.rs
  src/settings/target/kv_namespace.rs
  src/settings/target/site.rs
  src/settings/target/target.rs
Labels: category - refactor, priority - low, status - needs review

#857 run-wrangler.js: send error to stderr and exit 1 if child process has an error
  npm/run-wrangler.js
Labels: changelog - fix, status - needs review

#854 Remove the fixtures directory
  tests/build.rs
  tests/fixture/mod.rs
  tests/fixtures/simple_js/index.js
  tests/fixtures/simple_js/package.json
  tests/fixtures/simple_rust/Cargo.toml
  tests/fixtures/simple_rust/src/lib.rs
  tests/fixtures/simple_rust/src/utils.rs
  tests/fixtures/simple_rust/worker/worker.js
  tests/fixtures/webpack_function_config_js/index.js
  tests/fixtures/webpack_function_config_js/package.json
  tests/fixtures/webpack_function_config_js/webpack.config.js
  tests/fixtures/webpack_function_promise_config_js/index.js
  tests/fixtures/webpack_function_promise_config_js/package.json
  tests/fixtures/webpack_multiple_config/index.js
  tests/fixtures/webpack_multiple_config/package.json
  tests/fixtures/webpack_promise_config_js/index.js
  tests/fixtures/webpack_promise_config_js/package.json
  tests/fixtures/webpack_promise_config_js/webpack.config.js
  tests/fixtures/webpack_simple_js/index.js
  tests/fixtures/webpack_simple_js/package.json
  tests/fixtures/webpack_single_js_missing_package_main/index.js
  tests/fixtures/webpack_single_js_missing_package_main/package.json
  tests/fixtures/webpack_single_js_use_package_main/index.js
  tests/fixtures/webpack_single_js_use_package_main/package.json
  tests/fixtures/webpack_specify_config/index.js
  tests/fixtures/webpack_specify_config/package.json
  tests/fixtures/webpack_target_node/index.js
  tests/fixtures/webpack_target_node/package.json
  tests/fixtures/webpack_target_web/index.js
  tests/fixtures/webpack_target_web/package.json
  tests/fixtures/webpack_target_webworker/index.js
  tests/fixtures/webpack_target_webworker/package.json
  tests/fixtures/webpack_wast/index.js
  tests/fixtures/webpack_wast/module.wast
  tests/fixtures/webpack_wast/package.json
  tests/fixtures/webpack_wast/webpack.config.js
  tests/preview.rs
  tests/utils/mod.rs
Labels: category - refactor, changelog - maintenance, status - needs review

#842 Add credential checking logic when auth params are provided in wrangler config
  Cargo.lock
  Cargo.toml
  src/commands/config/mod.rs
  src/http.rs
  src/main.rs
  tests/config.rs
Labels: priority - critical, status - work in progress

#839 Adds error message for site with non-trailing asterisk
  src/commands/publish/mod.rs
Labels: changelog - feature, status - needs review

#868 Update demo gif
  wrangler-demo.gif
Labels: changelog - maintenance, priority - critical, status - needs review

#869 Clean up build fixture after asserting success
  tests/build.rs
Labels: changelog - maintenance, priority - critical, status - needs review

#880 Some environment variable precedence tests and messaging improvements
  src/commands/config/mod.rs
  src/commands/preview/upload.rs
  src/main.rs
  src/settings/environment.rs
  src/settings/global_user.rs
  src/terminal/message.rs
Labels: status - needs review

#879 Prefer environment variables over config files
  Cargo.lock
  Cargo.toml
  src/commands/config/mod.rs
  src/commands/preview/upload.rs
  src/main.rs
  src/settings/environment.rs
  src/settings/global_user.rs
  src/settings/mod.rs
  src/terminal/message.rs
Labels: category - refactor, changelog - feature, priority - critical, status - needs review

#864 🎰 1.6.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/README.md
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: priority - critical

#890 Rename proxy to dev
  src/commands/mod.rs
  src/commands/preview/dev_server.rs
  src/commands/preview/mod.rs
  src/main.rs
  src/terminal/emoji.rs
Labels: changelog - feature

#891 Fixes README formatting
  README.md
Labels: changelog - docs, status - needs review

#893 Make azure use latest rustc
  ci/azure-install-rust.yml
Labels: changelog - maintenance, status - needs review

#895 Install nightly for nightly builds
  azure-pipelines.yml
Labels: changelog - maintenance

#898 Actually actually use nightly builds
  ci/azure-install-rust.yml
Labels: changelog - maintenance, status - needs review

#914 Refactor: Use cloudflare-rs for calls to routes endpoints
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/settings/global_user.rs
Labels: category - refactor, cross-team - cloudflare-rs, priority - critical, status - blocked, status - needs review, subject - routes
