Repository cloudflare/wrangler-legacy, pull requests merged in 2019-04, with the labels that each got.

#54 Small tweaks - typo and formatting
  README.md
Labels: changelog - docs

#55 DRY version number
  src/main.rs
Labels: changelog - fix, needs review

#56 Use existing get_wrangler_cache function
  src/main.rs
Labels: changelog - maintenance, needs review

#51 improve CI, make release binaries
  azure-pipelines.yml
  ci/azure-create-tarball.yml
Labels: changelog - feature, changelog - maintenance

#23 switch on API plan
  src/commands/config.rs
  src/commands/publish/mod.rs
  src/commands/whoami.rs
  src/main.rs
  src/user/account.rs
  src/user/mod.rs
  src/user/settings.rs
Labels: changelog - feature

#57 per project config, wrangler.toml
  README.md
  src/commands/config.rs
  src/commands/generate.rs
  src/commands/mod.rs
  src/commands/publish/mod.rs
  src/commands/whoami.rs
  src/main.rs
  src/user/account.rs
  src/user/mod.rs
  src/user/settings.rs
Labels: changelog - feature

#64 fix(publish): no need to modify gen'd js
  src/commands/publish/mod.rs
Labels: changelog - maintenance

#65 route
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/commands/whoami.rs
  src/main.rs
  src/user/mod.rs
Labels: changelog - feature

#74 properly quote commands
  src/commands/build.rs
  src/commands/generate.rs
  src/commands/publish/route.rs
Labels: needs cargo fmt
