Repository cloudflare/wrangler-legacy, pull requests merged in 2019-05, with the labels that each got.

#78 fix(command): unbreak nix
  src/commands/build.rs
  src/commands/generate.rs
  src/commands/publish/mod.rs
  src/install/mod.rs
  src/main.rs
  src/user/settings.rs
Labels: needs review

#72 feat(generate): default to js template
  src/commands/build.rs
  src/commands/generate.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/route.rs
  src/main.rs
  src/user/account.rs
  src/user/mod.rs
  src/user/settings.rs
Labels: changelog - feature, needs docs, needs rebase, needs review

#75 Use underlying wrangler-js
  src/commands/build.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/main.rs
  src/user/settings.rs
  src/wranglerjs/mod.rs
Labels: work in progress

#103 fix(gen): don't rename to match rust conventions
  src/commands/generate.rs
Labels: needs review

#99 Use main in pkg json for publishing and preview single file js projects
  src/commands/publish/mod.rs
  src/commands/publish/package.rs
  src/commands/publish/preview/mod.rs
Labels: needs review

#118 Route overwrite
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
Labels: needs review

#105 chore: emoji fallbacks
  Cargo.lock
  Cargo.toml
  src/commands/build.rs
  src/commands/config.rs
  src/commands/generate.rs
  src/commands/whoami.rs
  src/emoji.rs
  src/main.rs
Labels: needs cargo fmt

#94 Use Webpack as backend
  src/commands/build.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/main.rs
  src/user/settings.rs
  src/wranglerjs/mod.rs
  wrangler-js/.gitignore
  wrangler-js/index.js
  wrangler-js/package.json
Labels: changes requested

#121 Test this thing
  Cargo.lock
  Cargo.toml
  azure-pipelines.yml
  ci/azure-install-node.yml
  src/commands/build.rs
  src/commands/config.rs
  src/commands/generate.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/route.rs
  src/commands/whoami.rs
  src/main.rs
  src/settings/global_user.rs
  src/settings/mod.rs
  src/settings/project.rs
  src/user/account.rs
  src/user/mod.rs
  src/wranglerjs/mod.rs
  tests/build.rs
  tests/generate.rs
  tests/help.rs
  tests/webpack_simple_js/index.js
  tests/webpack_simple_js/package.json
  tests/webpack_simple_js/webpack.config.js
Labels: work in progress

#146 feat(subdomain): add ability to add subdomain
  src/commands/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/commands/subdomain.rs
  src/emoji.rs
  src/main.rs
  src/settings/project.rs
  tests/build.rs
Labels: needs review

#156 fix(webpack): generate valid json
  src/wranglerjs/mod.rs
Labels: needs review

#158 CI: add wranglerjs release
  azure-pipelines.yml
  ci/azure-create-tarball.yml
  wranglerjs/.gitignore
  wranglerjs/index.js
  wranglerjs/package.json
Labels: work in progress

#160 initial kv namespace support
  src/commands/publish/mod.rs
  src/settings/project.rs
Labels: needs review

#165 fix: Windows commands
  src/wranglerjs/mod.rs
  tests/build.rs
  wranglerjs/index.js
  wranglerjs/package.json
Labels: needs rebase
