Repository cloudflare/wrangler-legacy, pull requests merged in 2019-09, with the labels that each got.

#325 feat #323: Allow fn & promise from webpack config
  tests/build.rs
  tests/fixtures/webpack_function_config_js/index.js
  tests/fixtures/webpack_function_config_js/package.json
  tests/fixtures/webpack_function_config_js/webpack.config.js
  tests/fixtures/webpack_function_promise_config_js/index.js
  tests/fixtures/webpack_function_promise_config_js/package.json
  tests/fixtures/webpack_function_promise_config_js/webpack.config.js
  tests/fixtures/webpack_promise_config_js/index.js
  tests/fixtures/webpack_promise_config_js/package.json
  tests/fixtures/webpack_promise_config_js/webpack.config.js
  wranglerjs/index.js
Labels: changelog - feature, status - changes requested, subject - webpack

#490 feat: use target webworker
  src/commands/build/wranglerjs/bundle.rs
  tests/build.rs
  tests/fixtures/webpack_target_web/index.js
  tests/fixtures/webpack_target_webworker/index.js
  wranglerjs/index.js
Labels: priority - critical, subject - webpack

#503 Update KV Subcommand docs page
  docs/content/kv_commands.md
Labels: changelog - docs, priority - critical, status - needs review, subject - kv

#507 Gabbi/url encode
  src/commands/kv/create_namespace.rs
  src/commands/kv/delete_bulk.rs
  src/commands/kv/delete_key.rs
  src/commands/kv/delete_namespace.rs
  src/commands/kv/list_keys.rs
  src/commands/kv/list_namespaces.rs
  src/commands/kv/mod.rs
  src/commands/kv/read_key.rs
  src/commands/kv/rename_namespace.rs
  src/commands/kv/write_bulk.rs
  src/commands/kv/write_key.rs
Labels: priority - critical, status - needs review, subject - kv

#511 Gabbi/add interactive delete
  docs/content/kv_commands.md
  src/commands/kv/delete_bulk.rs
  src/commands/kv/delete_key.rs
  src/commands/kv/delete_namespace.rs
  src/commands/kv/list_keys.rs
  src/commands/kv/mod.rs
  src/commands/kv/write_bulk.rs
  src/main.rs
Labels: category - feature, priority - critical, subject - kv

#520 Update usage of cloudflare::Credentials::User -> UserAuthKey
  Cargo.lock
  src/settings/global_user.rs
Labels: changelog - fix, priority - critical, status - needs review, subject - kv

#514 Add bucket::upload, bucket::delete
  docs/content/kv_commands.md
  src/commands/kv/bucket.rs
  src/commands/kv/delete_bulk.rs
  src/commands/kv/mod.rs
  src/commands/kv/write_bulk.rs
  src/commands/publish/mod.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#526 refactor: pass project to kv commands in prep for environments
  src/commands/kv/create_namespace.rs
  src/commands/kv/delete_bulk.rs
  src/commands/kv/delete_key.rs
  src/commands/kv/delete_namespace.rs
  src/commands/kv/list_keys.rs
  src/commands/kv/list_namespaces.rs
  src/commands/kv/mod.rs
  src/commands/kv/read_key.rs
  src/commands/kv/rename_namespace.rs
  src/commands/kv/write_bulk.rs
  src/commands/kv/write_key.rs
  src/main.rs
Labels: category - refactor, priority - critical, status - needs review, subject - kv

#527 refactor: organize kv by command type
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/mod.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/mod.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/mod.rs
  src/commands/kv/namespace/rename.rs
  src/main.rs
Labels: category - refactor, priority - low, status - needs review, subject - kv

#530 refactor: add kv bucket dir, replace POC code with bucket commands
  src/commands/kv/bucket/delete.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/publish/mod.rs
  src/main.rs
Labels: category - refactor, priority - critical, status - needs review, subject - kv

#528 Fix javascript live preview for linux
  src/commands/build/watch/mod.rs
  src/commands/build/watch/watcher.rs
Labels: priority - critical, status - needs review

#525 Disallow duplicate environment names
  src/settings/project/mod.rs
  src/settings/project/tests/tomls/kv_namespaces.toml
Labels: changelog - feature, status - needs review

#533 Add deprecation warning if 'private' is in top-level config or any en…
  src/settings/project/mod.rs
Labels: priority - critical, status - needs review

#535 Have live reload preview watch over entire rust worker directory
  src/commands/build/watch/mod.rs
Labels: priority - critical, status - needs review

#531 Alewis/refactor key list
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/mod.rs
Labels: category - refactor, priority - critical, status - needs rebase, subject - kv

#534 Refactor environment parsing
  src/main.rs
  src/settings/project/mod.rs
Labels: changelog - feature, status - needs review

#500 Environments Documentation
  README.md
  docs/environments.md
Labels: changelog - docs, status - needs review

#539 Complete renaming of project to target
  src/commands/build/mod.rs
  src/commands/build/watch/mod.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/route.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/subdomain.rs
  src/main.rs
  src/settings/mod.rs
  src/settings/project/project_type.rs
  src/settings/target/kv_namespace.rs
  src/settings/target/mod.rs
  src/settings/target/target_type.rs
  src/settings/target/tests/mod.rs
  src/settings/target/tests/tomls/default.toml
  src/settings/target/tests/tomls/environments.toml
  src/settings/target/tests/tomls/invalid_environments.toml
  src/settings/target/tests/tomls/kv_namespaces.toml
  src/settings/target/tests/tomls/legacy/default.toml
  src/settings/target/tests/tomls/legacy/kv_namespaces.toml
  src/settings/target/tests/tomls/no_default.toml
Labels: changelog - maintenance

#494 Remove link to docs for installation because they link back to wrangler README
  README.md
Labels: changelog - docs

#542 Gabbi/add kv env support
  docs/content/environments.md
  docs/content/kv_commands.md
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/rename.rs
  src/main.rs
  src/settings/target/mod.rs
Labels: priority - critical, status - needs review, subject - kv

#555 Gabbi/remove rename kv subcommand
  docs/content/kv_commands.md
  src/commands/kv/namespace/mod.rs
  src/commands/kv/namespace/rename.rs
  src/main.rs
Labels: priority - critical, status - needs review, subject - kv

#556 Update kv namespaces configuration documentation
  README.md
Labels: changelog - docs, priority - critical, subject - kv

#557 Gabbi/perscriptive namespace titles
  src/commands/kv/namespace/create.rs
  src/main.rs
Labels: priority - critical, status - needs review, subject - kv

#544 Add environment documentation to readme
  README.md
  docs/environments.md
Labels: changelog - docs, priority - critical, status - needs review

#578 Use notify-forked
  Cargo.lock
  Cargo.toml
  src/commands/build/watch/mod.rs
  src/commands/build/watch/watcher.rs
  src/commands/build/wranglerjs/mod.rs
Labels: changelog - fix

#584 Reduce output from publish command
  docs/environments.md
  src/commands/publish/mod.rs
Labels: changelog - feature, status - needs review

#405 Feat kv commands
  Cargo.lock
  Cargo.toml
  README.md
  docs/content/environments.md
  docs/content/kv_commands.md
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/mod.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/mod.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/mod.rs
  src/commands/mod.rs
  src/main.rs
  src/settings/global_user.rs
  src/settings/target/mod.rs
  src/terminal/emoji.rs
Labels: changelog - feature, feature branch, priority - critical, status - needs cargo fmt, status - needs review, subject - kv

#587 Use notify instead of notify-forked
  Cargo.lock
  Cargo.toml
  src/commands/build/watch/mod.rs
  src/commands/build/watch/watcher.rs
  src/commands/build/wranglerjs/mod.rs
Labels: category - maintenance

#586 Ensure --binding, --namespace-id args are only specified for last subcommands in kv subcommand sequence
  src/main.rs
Labels: priority - critical, status - needs review, subject - kv

#585 Add documentation for init to the README
  README.md
Labels: changelog - docs, status - needs review

#593 remove duplicate namespace-id and binding args
  src/main.rs
Labels: changelog - fix, subject - kv

#592 Implement namespace-id and binding arguments for kv:bucket
  docs/content/kv_commands.md
  src/main.rs
Labels: changelog - docs, changelog - feature, subject - kv

#594 Fixes (some) clippy warnings
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
Labels: changelog - maintenance

#597 fix suggested value for kv-namespaces in wrangler.toml to use equals sign, not colons
  src/commands/kv/namespace/create.rs
Labels: priority - critical, status - needs review

#583 Add keywords for npm SEO
  npm/package.json
Labels: changelog - maintenance, status - needs review

#604 ensure binding or namespace-id are required in Clap ArgGroup
  src/main.rs
Labels: priority - critical

#605 Different emojis for different commands
  src/main.rs
  src/terminal/emoji.rs
Labels: changelog - fix

#613 Refactor kv::print_error to kv::format_error and hoist error printing out of private kv functions
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
Labels: priority - critical, status - needs review, subject - kv

#598 feat #450: support negate flags for publish
  src/commands/publish/mod.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#614 Implement crude version of `kv:bucket sync` that does not use hashes to determine changed files yet
  src/commands/kv/bucket/delete.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/list.rs
  src/main.rs
Labels: priority - critical, status - needs review, subject - kv

#615 Alewis/sites interface
  src/commands/kv/mod.rs
  src/commands/kv/namespace/mod.rs
  src/commands/kv/namespace/site.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/upload_form/mod.rs
  src/main.rs
  src/settings/target/mod.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - site

#601 Implement large bucket uploads split across multiple bulk KV API requests
  src/commands/kv/bucket/upload.rs
Labels: priority - critical, status - needs review, subject - kv

#616 Alewis/root toml
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/package.rs
  src/commands/publish/upload_form/mod.rs
  src/settings/target/mod.rs
Labels: category - feature, priority - critical, status - needs review, subject - site

#626 Add verbose logging option for `kv:bucket sync/upload`
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/mod.rs
  src/main.rs
Labels: priority - critical, status - needs review, subject - kv

#632 Add support for generating and initializing site projects
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/namespace/site.rs
  src/commands/publish/mod.rs
  src/commands/publish/package.rs
  src/commands/publish/upload_form/mod.rs
  src/main.rs
  src/settings/target/mod.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - site

#629 Asset Manifest
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/commands/publish/upload_form/text_blob.rs
  src/settings/binding.rs
Labels: changelog - feature, subject - kv

#635 Fix asset manifest logic to ensure uploaded files remain on Workers KV remote
  src/commands/kv/bucket/mod.rs
Labels: priority - critical

#633 Better file support for kv:put
  src/commands/kv/key/put.rs
Labels: status - needs review

#638 Alewis/default site bucket
  src/commands/generate.rs
  src/commands/init.rs
  src/settings/target/mod.rs
Labels: category - feature, priority - critical, status - needs review, subject - site

#509 feat: kv additions
  Cargo.lock
  Cargo.toml
  docs/content/kv_commands.md
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/kv/bucket/delete.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/mod.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/mod.rs
  src/commands/kv/namespace/site.rs
  src/commands/publish/mod.rs
  src/commands/publish/package.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/commands/publish/upload_form/text_blob.rs
  src/main.rs
  src/settings/binding.rs
  src/settings/target/kv_namespace.rs
  src/settings/target/mod.rs
  src/settings/target/tests/mod.rs
  src/terminal/emoji.rs
Labels: changelog - feature, feature branch, priority - critical, subject - kv

#649 1.4.0-rc.0
  Cargo.lock
  Cargo.toml
  npm/install-wrangler.js
  npm/package.json
Labels: status - needs review

#651 Update upload.rs
  src/commands/kv/bucket/upload.rs
Labels: status - needs review

#652 feat #642: use real templates
  src/commands/build/wranglerjs/mod.rs
  src/main.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - site

#654 Alewis/remove buckets
  docs/content/kv_commands.md
  src/commands/kv/bucket/delete.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/mod.rs
  src/main.rs
  src/terminal/emoji.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - kv

#665 Ensure KV subcommands check for presence of required fields in wrangler.toml
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/site.rs
Labels: priority - critical, status - needs review, subject - kv

#686 Add validation for workers names in wrangler init and wrangler generate
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/kv/namespace/create.rs
  src/commands/mod.rs
  src/commands/publish/mod.rs
Labels: priority - critical, status - needs review

#664 Sync that only uploads files if their contents have changed from the corresponding file in remote
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
Labels: priority - critical, status - needs review, subject - kv

#684 Add error messages for improperly configured buckets
  src/commands/publish/mod.rs
Labels: changelog - feature

#693 Add preview functionality for static assets
  src/commands/kv/namespace/site.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/upload_form/mod.rs
Labels: priority - critical, status - needs review, subject - site

#700 Use display not lossy string for path
  src/commands/publish/mod.rs
Labels: changelog - maintenance

#708 Insert hashes before extensions in asset manifest to ease content-type detection
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/namespace/site.rs
  src/commands/publish/preview/mod.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - site

#717 Only build asset manifest once
  src/commands/kv/bucket/manifest.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/upload_form/mod.rs
Labels: changelog - maintenance

#713 Add message for ignoring files
  src/commands/kv/bucket/manifest.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/upload_form/mod.rs
Labels: changelog - feature, status - work in progress

#710 Ignore uploading node_modules
  src/commands/kv/bucket/manifest.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/upload_form/mod.rs
Labels: priority - critical, status - work in progress, subject - site

#709 Custom webpack configuration behavior
  src/commands/build/wranglerjs/mod.rs
Labels: changelog - feature, subject - site

#714 Add live reload for static sites
  src/commands/build/wranglerjs/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/upload.rs
Labels: category - feature, priority - critical, subject - site

#725 Provide closed error path for unauthed preview with sites
  src/commands/publish/preview/upload.rs
Labels: priority - critical, status - needs review

#724 Add documentation for webpack behavior
  README.md
  docs/content/webpack.md
Labels: changelog - docs

#726 Install latest version when binary installing
  src/install/mod.rs
Labels: changelog - fix

#730 Ensure creating namespace message is only printed when a namespace is actually created
  src/commands/kv/namespace/site.rs
Labels: priority - critical, status - needs review

#729 Add wrangler/version/site for site API requests
  src/commands/kv/key/get.rs
  src/commands/kv/key/put.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/preview/upload.rs
  src/commands/publish/route.rs
  src/commands/subdomain.rs
  src/http.rs
  src/install/krate.rs
Labels: changelog - maintenance, status - needs review

#733 Add message about upgrading account
  src/commands/kv/namespace/site.rs
Labels: changelog - feature, status - needs review, subject - site

#737 Support pagination of KV namespace API to look at all namespaces
  Cargo.lock
  Cargo.toml
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/site.rs
  src/commands/publish/mod.rs
Labels: bug, priority - critical

#728 Link to sites docs in README
  README.md
Labels: status - blocked
