Repository cloudflare/wrangler-legacy, pull requests merged in 2019-12, with the labels that each got.

#918 Alewis/refactor routes
  Cargo.lock
  Cargo.toml
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/settings/target/environment.rs
  src/settings/target/manifest.rs
  src/settings/target/mod.rs
  src/settings/target/route.rs
  src/settings/target/target.rs
Labels: category - refactor, priority - critical, status - needs review, subject - routes

#917 [dev] Module refactor
  Cargo.toml
  src/commands/dev/mod.rs
  src/commands/dev/server_config/host.rs
  src/commands/dev/server_config/listening_address.rs
  src/commands/dev/server_config/mod.rs
  src/commands/mod.rs
  src/commands/preview/mod.rs
  src/main.rs
Labels: category - refactor, status - needs review

#921 Update cloudflare-rs version for routes endpoints
  Cargo.lock
  Cargo.toml
Labels: changelog - maintenance, status - needs review, subject - routes

#922 Alewis/publish multiple routes
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/settings/target/route.rs
  src/settings/target/target.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - routes

#927 Alewis/improve test fixtures
  tests/build.rs
  tests/fixture/mod.rs
  tests/fixture/wrangler_toml.rs
  tests/preview.rs
Labels: category - refactor, priority - critical, status - needs review

#929 Remove deprecated kv-namespace config check
  src/settings/target/manifest.rs
Labels: category - maintenance

#931 feat(init): improve error message for init site with existing toml
  src/commands/init/mod.rs
Labels: changelog - feature

#932 Adds helpful error message on authentication error
  src/commands/publish/mod.rs
Labels: changelog - feature

#919 add cfg attribute
  src/commands/config/mod.rs
Labels: changelog - maintenance

#935 Removes compiler warnings
  src/settings/environment.rs
  src/settings/global_user.rs
Labels: changelog - maintenance, status - needs review

#939 update toml test fixture path
  src/settings/toml/tests/mod.rs
Labels: bug

#936 Addresses clippy warnings
  src/commands/build/mod.rs
  src/commands/build/watch/mod.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate/mod.rs
  src/commands/init/mod.rs
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/key_list.rs
  src/commands/kv/key/list.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/kv/namespace/list.rs
  src/commands/kv/namespace/site.rs
  src/commands/preview/mod.rs
  src/commands/preview/upload.rs
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/commands/subdomain/mod.rs
  src/http.rs
  src/main.rs
  src/settings/environment.rs
  src/settings/global_user.rs
  src/settings/mod.rs
  src/settings/toml/environment.rs
  src/settings/toml/kv_namespace.rs
  src/settings/toml/manifest.rs
  src/settings/toml/mod.rs
  src/settings/toml/site.rs
  src/settings/toml/target.rs
  src/settings/toml/target_type.rs
  src/settings/toml/tests/mod.rs
  src/settings/toml/tests/tomls/default.toml
  src/settings/toml/tests/tomls/environments.toml
  src/settings/toml/tests/tomls/invalid_environments.toml
  src/settings/toml/tests/tomls/kv_namespaces.toml
  src/settings/toml/tests/tomls/no_default.toml
  tests/fixture/mod.rs
Labels: changelog - maintenance, status - needs review

#937 Provide helpful error when user accidentally puts kv-namespace information under [site]
  Cargo.lock
  Cargo.toml
  src/settings/toml/manifest.rs
  src/settings/toml/site.rs
Labels: category - maintenance, status - needs rebase, status - needs review, subject - site

#886 [dev] Handle response headers
  src/commands/dev/mod.rs
Labels: changelog - feature, status - needs review

#862 Use binary-install for npm
  npm/binary.js
  npm/install-wrangler.js
  npm/npm-shrinkwrap.json
  npm/package.json
  npm/run-wrangler.js
Labels: changelog - maintenance, status - needs review

#884 [dev] Handles cf-ew-raw- headers
  src/commands/dev/headers.rs
  src/commands/dev/mod.rs
Labels: status - needs review

#968 [dev] Return proper response code
  src/commands/dev/headers.rs
  src/commands/dev/mod.rs
Labels: status - needs review

#923 [dev] Output console.log messages
  Cargo.lock
  Cargo.toml
  logs/connection.log
  src/commands/dev/mod.rs
  src/commands/dev/socket/client.rs
  src/commands/dev/socket/mod.rs
  src/main.rs
Labels: status - needs review

#971 Better error message when custom webpack fails
  src/commands/build/wranglerjs/mod.rs
Labels: changelog - feature, priority - low, status - needs review, subject - site

#957 Alewis/custom webpack config for sites
  src/commands/build/wranglerjs/mod.rs
  tests/build.rs
  tests/fixture/mod.rs
  tests/fixture/wrangler_toml.rs
  tests/preview.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - site, subject - webpack

#956 Use indicatif to provide a more intuitive representation of upload progress
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/upload.rs
Labels: category - maintenance, priority - nice to have, status - needs review

#973 give api_client more specific name
  src/commands/config/mod.rs
  src/commands/kv/mod.rs
  src/http.rs
Labels: category - refactor, priority - low, status - needs review
