Repository cloudflare/wrangler-legacy, pull requests merged in 2019-07, with the labels that each got.

#267 Add an authenticated HTTP client
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/commands/subdomain.rs
  src/http.rs
Labels: category - maintenance, changelog - maintenance

#279 Refactor: Conditional per command in main
  src/main.rs
Labels: changelog - maintenance

#285 Use serde for metadata
  src/commands/build/wranglerjs/bundle.rs
  src/settings/binding.rs
  src/settings/metadata.rs
  src/settings/mod.rs
Labels: changelog - maintenance, status - needs review

#272 Refactor wranglerjs
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/mod.rs
Labels: changelog - maintenance

#287 Update README with new config and update information
  README.md
Labels: category - docs, changelog - docs

#271 Check wrangler.toml before doing publish steps
  Cargo.lock
  Cargo.toml
  src/cache.rs
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/generate.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/install/mod.rs
  src/main.rs
Labels: changelog - fix, status - needs review

#283 Better node install documentation
  README.md
Labels: changelog - docs

#258 Adds formatting, linting, and testing pre-commit hook
  .rusty-hook.toml
  Cargo.lock
  Cargo.toml
Labels: changelog - maintenance, status - changes requested

#291 ci: activate backtracing
  azure-pipelines.yml
Labels: changelog - maintenance

#294 fix: warnings
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/bundle.rs
  src/terminal/emoji.rs
  src/terminal/message.rs
Labels: category - maintenance, changelog - maintenance

#215 Add kv_namespaces in metadata
  README.md
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/publish/mod.rs
  src/settings/binding.rs
  src/settings/project.rs
Labels: changelog - feature

#308 Remove pre-push hooks
  .rusty-hook.toml
  Cargo.lock
  Cargo.toml
Labels: changelog - maintenance, status - needs review

#309 Use rust template for rust project
  src/main.rs
Labels: changelog - fix, status - needs review

#307 Stop cleaning webpack build artifacts
  src/commands/build/wranglerjs/bundle.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/build/wranglerjs/output.rs
  wranglerjs/index.js
Labels: changelog - fix, status - needs review

#231 feature: compare bundle size to limit
  src/commands/build/wranglerjs/mod.rs
  src/commands/build/wranglerjs/output.rs
Labels: changelog - feature, priority - critical, status - needs review

#319 Update README to include KV config info
  README.md
Labels: changelog - docs, status - needs review, subject - kv

#333 feat kv config
  src/commands/publish/mod.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/settings/binding.rs
  src/settings/project/kv_namespace.rs
  src/settings/project/mod.rs
  src/settings/project/project_type.rs
  src/settings/project/tests/mod.rs
  src/settings/project/tests/tomls/default.toml
  src/settings/project/tests/tomls/kv_namespaces.toml
Labels: changelog - feature, status - needs review, subject - kv

#327 Better error printing
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/terminal/emoji.rs
Labels: changelog - feature, status - needs review

#350 Add issue templates for bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: changelog - maintenance

#286 Change global config perm
  src/commands/config.rs
  tests/config.rs
Labels: category - feature, changelog - feature, priority - critical, status - needs tests

#225 Settings: make global config file optional
  src/settings/global_user.rs
Labels: changelog - feature, changelog - fix

#268 feat(docs): add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: changelog - maintenance, priority - critical

#329 feat: unify upload form building
  src/commands/build/wranglerjs/bundle.rs
  src/commands/publish/mod.rs
  src/commands/publish/preview/mod.rs
  src/commands/publish/script_upload_form.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/commands/publish/upload_form/wasm_module.rs
  src/settings/binding.rs
  tests/build.rs
Labels: category - feature, category - refactor, changelog - feature

#334 feat: Support KV Namespace Configuration
  README.md
  src/commands/publish/mod.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/settings/binding.rs
  src/settings/project/kv_namespace.rs
  src/settings/project/mod.rs
  src/settings/project/project_type.rs
  src/settings/project/tests/mod.rs
  src/settings/project/tests/tomls/default.toml
  src/settings/project/tests/tomls/kv_namespaces.toml
Labels: changelog - feature, status - needs review, subject - kv

#239 Use stdin instead of arguments for wrangler config
  Cargo.lock
  Cargo.toml
  src/commands/config.rs
  src/main.rs
  src/settings/global_user.rs
  src/terminal/emoji.rs
  tests/config.rs
Labels: category - refactor, changelog - fix, priority - critical

#365 release nits + test fails
  src/settings/global_user.rs
  tests/config.rs
Labels: changelog - maintenance, status - needs review

#370 nit: Make binding name capitalized in readme
  README.md
Labels: changelog - docs, priority - critical

#373 make clippy happy
  src/commands/build/wranglerjs/output.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/project_assets.rs
  src/commands/publish/upload_form/wasm_module.rs
  src/main.rs
Labels: changelog - maintenance, priority - critical

#369 add check + error message for pre 1.1.0 kv namespace format
  src/settings/project/mod.rs
  src/terminal/message.rs
Labels: changelog - maintenance, priority - critical

#356 Update README.md
  README.md
Labels: status - blocked

#288 🔑 Wrangler 1.1.0 Release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: priority - critical, status - changes requested, status - work in progress
