Repository cloudflare/wrangler-legacy, pull requests merged in 2020-05, with the labels that each got.

#1236 Adds spinner to wrangler tail setup
  src/commands/tail/mod.rs
  src/tail/session.rs
Labels: category - feature, status - needs review

#469 Fixes #58 - Auto increment for default name
  src/commands/generate/mod.rs
Labels: changelog - feature, priority - low, status - changes requested

#1238 Adds 🦚emoji to tail command
  src/commands/tail/mod.rs
  src/main.rs
  src/terminal/emoji.rs
Labels: changelog - feature, status - needs review

#1242 log server return 400 instead of 404
  src/tail/log_server.rs
Labels: changelog - fix, status - needs review

#1247 [tail] improve error messaging
  Cargo.lock
  Cargo.toml
  src/commands/tail/mod.rs
  src/tail/mod.rs
Labels: changelog - N/A

#1248 standardizes colors in stdout
  src/commands/config/mod.rs
  src/commands/dev/mod.rs
  src/commands/preview/upload.rs
  src/commands/publish/mod.rs
  src/commands/whoami/mod.rs
  src/main.rs
  src/settings/global_user.rs
  src/settings/toml/manifest.rs
  src/terminal/mod.rs
  src/terminal/styles.rs
Labels: changelog - feature, status - needs review

#1252 document build.rs
  build.rs
Labels: changelog - maintenance

#1256 Alewis/verbose tail
  src/commands/tail/mod.rs
  src/main.rs
  src/tail/mod.rs
  src/tail/session.rs
  src/tail/tunnel.rs
Labels: changelog - N/A, priority - low, status - needs review, subject - logging

#1253 move util struct where it's used
  src/commands/build/wranglerjs/guarded_command.rs
  src/commands/build/wranglerjs/mod.rs
  src/lib.rs
Labels: category - refactor

#1251 remove overly enthusiastic dev error handling
  src/commands/dev/gcs/setup.rs
Labels: changelog - fix

#1239 suggest `wrangler init` if wrangler.toml does not exist
  src/settings/toml/manifest.rs
  src/settings/toml/tests/mod.rs
Labels: changelog - feature, priority - nice to have, status - needs review

#1260 update bucket deprecation notice to target 1.10.0
  src/commands/publish/mod.rs
Labels: category - refactor

#1258 Alewis/delete tail
  Cargo.lock
  Cargo.toml
  src/tail/mod.rs
  src/tail/session.rs
Labels: changelog - N/A, cross-team - cloudflare-rs, priority - low, status - blocked, subject - logging

#1182 Alewis/wrangler tail
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
  src/commands/mod.rs
  src/commands/tail/mod.rs
  src/http/cf.rs
  src/http/mod.rs
  src/install/mod.rs
  src/lib.rs
  src/main.rs
  src/tail/log_server.rs
  src/tail/mod.rs
  src/tail/session.rs
  src/tail/shutdown.rs
  src/tail/tunnel.rs
  src/terminal/emoji.rs
Labels: feature branch, subject - logging

#1250 🦚 1.9.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release

#1264 move 'merge' instructions under publish
  RELEASE_CHECKLIST.md
Labels: changelog - N/A

#1273 move 'watch' to top level module
  src/commands/build/mod.rs
  src/commands/build/wranglerjs/mod.rs
  src/commands/dev/gcs/watch.rs
  src/commands/mod.rs
  src/commands/preview/mod.rs
  src/lib.rs
  src/watch/mod.rs
  src/watch/watcher.rs
Labels: changelog - N/A, status - needs review

#1277 Alewis/commands refactor build
  src/build/mod.rs
  src/commands/build.rs
  src/commands/dev/gcs/watch.rs
  src/commands/dev/mod.rs
  src/commands/mod.rs
  src/commands/preview/mod.rs
  src/commands/publish/mod.rs
  src/lib.rs
  src/main.rs
  src/upload/form/mod.rs
  src/watch/mod.rs
  src/wranglerjs/bundle.rs
  src/wranglerjs/guarded_command.rs
  src/wranglerjs/mod.rs
  src/wranglerjs/output.rs
Labels: changelog - N/A

#1278 Alewis/commands refactor mods
  src/commands/config.rs
  src/commands/generate.rs
  src/commands/init.rs
  src/commands/publish.rs
  src/commands/route.rs
  src/commands/secret.rs
  src/commands/subdomain.rs
  src/commands/tail.rs
  src/commands/whoami.rs
Labels: changelog - N/A

#1003 dont reinstall same binary versions
  Cargo.lock
  Cargo.toml
  src/build/mod.rs
  src/commands/generate.rs
  src/install/mod.rs
  src/terminal/emoji.rs
  src/watch/mod.rs
  src/wranglerjs/mod.rs
Labels: changelog - fix, status - needs review

#1280 remove debug flag from release profile
  Cargo.toml
Labels: changelog - N/A, status - needs review

#1285 refactor: move preview to top level directory
  src/commands/dev/gcs/setup.rs
  src/commands/mod.rs
  src/commands/preview.rs
  src/commands/preview/http_method.rs
  src/lib.rs
  src/main.rs
  src/preview/fiddle_messenger.rs
  src/preview/http_method.rs
  src/preview/mod.rs
  src/preview/request_payload.rs
  src/preview/upload.rs
Labels: changelog - N/A

#1272 [dev] checks if port is available before attempting to start server
  src/commands/dev/gcs/server.rs
  src/commands/dev/mod.rs
  src/commands/dev/server_config/listening_address.rs
  src/commands/dev/server_config/mod.rs
  src/main.rs
Labels: changelog - feature, status - needs review

#1276 [dev] reconnect socket after bad protocol message
  Cargo.lock
  Cargo.toml
  src/commands/dev/socket.rs
Labels: changelog - fix

#1269 removes redundant builds when watching
  src/commands/dev/gcs/watch.rs
  src/preview/mod.rs
  src/watch/mod.rs
Labels: changelog - fix, status - needs review

#1288 Adds Developing Wrangler section to Contribution Guide
  CONTRIBUTING.md
Labels: category - docs, changelog - N/A, status - needs review

#1290 updates license to wrangler@cloudflare
  LICENSE-MIT
Labels: changelog - N/A, status - needs review

#1289 removes --release from publish help
  src/main.rs
Labels: changelog - maintenance, status - needs review

#1110 add verbose argument acceptance to commands
  src/main.rs
Labels: changelog - feature, status - changes requested

#1305 low hanging clippy warnings
  src/commands/generate.rs
  src/fixtures/mod.rs
  src/installer.rs
  src/preview/mod.rs
  src/preview/request_payload.rs
  src/settings/global_user.rs
  src/tail/tunnel.rs
Labels: changelog - maintenance

#1306 fixes more clippy warnings
  src/commands/dev/gcs/server.rs
  src/commands/dev/gcs/watch.rs
  src/commands/dev/socket.rs
  src/commands/preview.rs
  src/lib.rs
  src/main.rs
  src/preview/http_method.rs
  src/preview/mod.rs
  src/settings/toml/tests/mod.rs
  src/tail/session.rs
  src/terminal/interactive.rs
  src/watch/watcher.rs
  src/wranglerjs/mod.rs
Labels: changelog - maintenance

#1307 🐎 1.9.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release, status - needs review

#1314 Updates Cargo.toml authors and description
  Cargo.toml
  npm/package.json
Labels: changelog - N/A, status - needs review

#1323 🐼 1.9.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: status - needs review

#1325 enforces no compiler warnings in CI
  .github/workflows/test.yml
  Cargo.toml
  src/lib.rs
  src/main.rs
Labels: changelog - N/A

#1324 Runs clippy in CI + enforce all formatting
  .github/workflows/lint.yml
  src/main.rs
Labels: category - maintenance, changelog - N/A

#1328 removes clippy allow redundant closure
  src/main.rs
Labels: changelog - N/A, status - needs review

#1326 Made version check only happen once a day
  src/version/version.rs
Labels: changelog - feature, status - needs review

#1331 Fetches latest version if version file is older than a day
  src/version/wrangler_version.rs
Labels: changelog - feature, status - needs review

#1329 Clean up apierrors and only include messages
  src/commands/kv/namespace/site.rs
Labels: changelog - feature, status - needs review

#1336 Add better error messages without breaking publish
  src/commands/kv/namespace/site.rs
Labels: changelog - feature, status - needs review

#1190 feat: message if wrangler needs updating
  src/commands/config.rs
  src/lib.rs
  src/main.rs
  src/settings/global_config.rs
  src/settings/global_user.rs
  src/settings/mod.rs
  src/terminal/styles.rs
  src/version/mod.rs
Labels: changelog - feature, status - needs review

#1345 adds security.md
  SECURITY.md
Labels: changelog - maintenance, status - needs review
