Repository cloudflare/wrangler-legacy, pull requests merged in 2020-04, with the labels that each got.

#1185 Alewis/tail support env
  src/commands/tail/mod.rs
  src/main.rs
Labels: priority - critical, status - needs review, subject - logging

#1189 Alewis/refactor tail
  src/commands/mod.rs
  src/commands/tail/mod.rs
  src/lib.rs
  src/main.rs
  src/tail/host.rs
  src/tail/mod.rs
  src/tail/session.rs
  src/tail/tunnel.rs
Labels: priority - critical, status - needs review, subject - logging

#1070 Sends custom user agent with cloudflare-rs
  src/commands/config/mod.rs
  src/commands/kv/key/get.rs
  src/commands/kv/key/put.rs
  src/commands/kv/mod.rs
  src/commands/preview/mod.rs
  src/commands/preview/upload.rs
  src/commands/publish/mod.rs
  src/commands/route/mod.rs
  src/commands/secret/mod.rs
  src/commands/subdomain/mod.rs
  src/commands/whoami/mod.rs
  src/deploy/mod.rs
  src/deploy/route.rs
  src/http.rs
  src/http/cf.rs
  src/http/feature.rs
  src/http/legacy.rs
  src/http/mod.rs
  src/install/krate.rs
Labels: changelog - feature, status - needs review

#1195 Alewis/handle sigint
  Cargo.toml
  src/tail/host.rs
  src/tail/log_server.rs
  src/tail/mod.rs
  src/tail/session.rs
  src/tail/tunnel.rs
Labels: priority - critical, status - needs cargo fmt, subject - logging

#1169 allow kv-namespaces AND kv_namespaces
  src/settings/toml/manifest.rs
  tests/parse.rs
Labels: changelog - feature, status - needs review

#1001 Added URL support for preview command
  Cargo.toml
  src/commands/preview/mod.rs
  src/commands/preview/request_payload.rs
  src/main.rs
  tests/preview.rs
Labels: changelog - feature, status - waiting on response

#1209 Alewis/interrupt session start
  Cargo.lock
  Cargo.toml
  src/tail/session.rs
  src/tail/shutdown.rs
Labels: subject - logging

#1211 1.9.0-rc.0
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release

#1213 reduce hover
  src/tail/session.rs
Labels: bug

#1215 distinguish between rc and full release steps, chunk steps
  RELEASE_CHECKLIST.md
Labels: category - docs, changelog - N/A, priority - nice to have, status - needs review

#1212 Add support for printing api token email on `whoami`
  src/commands/whoami/mod.rs
Labels: changelog - feature

#1220 refactor and document wrangler dev
  Cargo.lock
  Cargo.toml
  src/commands/dev/edge/headers.rs
  src/commands/dev/edge/server.rs
  src/commands/dev/edge/setup.rs
  src/commands/dev/gcs/headers.rs
  src/commands/dev/gcs/mod.rs
  src/commands/dev/gcs/server.rs
  src/commands/dev/gcs/setup.rs
  src/commands/dev/gcs/watch.rs
  src/commands/dev/mod.rs
  src/commands/dev/server_config/host.rs
  src/commands/dev/server_config/listening_address.rs
  src/commands/dev/server_config/mod.rs
  src/commands/dev/socket.rs
Labels: category - refactor, changelog - N/A

#1223 Better port selection
  src/commands/tail/mod.rs
  src/main.rs
  src/tail/log_server.rs
  src/tail/mod.rs
  src/tail/session.rs
  src/tail/tunnel.rs
Labels: changelog - N/A, status - needs review, subject - logging

#1221 use xxhash for asset manifest
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
Labels: changelog - feature, status - needs review

#1210 Fix typo in init command
  src/commands/init/mod.rs
Labels: changelog - fix

#1217 Add wrangler.toml to issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: changelog - N/A

#1231 add tests for find_open_port
  src/commands/tail/mod.rs
Labels: subject - logging
