Repository cloudflare/wrangler-legacy, pull requests merged in 2020-07, with the labels that each got.

#1350 Added parameter to override default location to config file
  src/commands/build.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/create.rs
  src/commands/kv/namespace/delete.rs
  src/commands/mod.rs
  src/commands/publish.rs
  src/commands/secret.rs
  src/commands/subdomain.rs
  src/deploy/route.rs
  src/main.rs
  src/preview/upload.rs
  src/settings/toml/deploy_config.rs
  src/settings/toml/manifest.rs
  src/sites/mod.rs
  src/tail/session.rs
  src/wranglerjs/mod.rs
  tests/build.rs
Labels: changelog - feature

#1428 Remove trailing spaces from Markdown
  README.md
  npm/README.md
Labels: changelog - maintenance

#1444 Removed unreachable code
  src/main.rs
Labels: changelog - maintenance

#1447 Added warning for site in unauthenticated preview
  src/preview/upload.rs
Labels: changelog - feature

#1448 Changed from matches to route subcommand matches
  src/main.rs
Labels: status - needs review

#1450 Direct cloudflared out to /dev/null
  src/tail/tunnel.rs
Labels: status - needs review

#1451 [dev] upload workers sites bindings for edge dev
  src/commands/dev/edge/mod.rs
  src/commands/dev/edge/server.rs
  src/commands/dev/edge/setup.rs
  src/commands/dev/mod.rs
Labels: changelog - fix

#1454 Fixes typo in error messages and code comments
  src/commands/dev/server_config/mod.rs
  src/deploy/route.rs
  src/wranglerjs/mod.rs
  src/wranglerjs/output.rs
Labels: changelog - maintenance

#1098 [dev] route authenticated dev requests to the edge
  src/commands/dev/edge/mod.rs
  src/commands/dev/edge/server.rs
  src/commands/dev/edge/setup.rs
  src/commands/dev/gcs/mod.rs
  src/commands/dev/gcs/server.rs
  src/commands/dev/mod.rs
  src/commands/dev/utils.rs
  src/main.rs
  src/preview/upload.rs
  src/settings/toml/deploy_config.rs
  src/upload/form/mod.rs
  src/upload/mod.rs
Labels: status - needs review, subject - wrangler dev

#1461 Check if rustc exists before building a Rust project type
  src/build/mod.rs
Labels: changelog - feature

#1291 [dev] connect to edge websocket
  src/commands/dev/edge/mod.rs
  src/commands/dev/edge/setup.rs
Labels: changelog - feature, subject - wrangler dev

#1469 dont wasm-opt in test
  tests/preview.rs
Labels: changelog - fix, status - needs review

#1467 Workers Unlimited => Workers Bundled
  src/kv/namespace/upsert.rs
Labels: changelog - maintenance, status - needs review

#1470 [dev] removes alpha warning message
  src/commands/dev/mod.rs
  src/commands/dev/server_config/mod.rs
  src/main.rs
Labels: status - needs review, subject - wrangler dev

#1472 [dev] update help text to 127.0.0.1
  src/main.rs
Labels: changelog - feature, subject - wrangler dev

#1473 🤏 1.11.0-rc.0
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release, status - needs review
