Repository cloudflare/wrangler-legacy, pull requests merged in 2020-01, with the labels that each got.

#981 Fix #958: Do not factor in .gitignore into workers sites upload directory traversal
  src/commands/kv/bucket/mod.rs
Labels: category - maintenance, priority - critical, status - needs review, subject - site

#982 Bump npm binary-install to 0.0.1
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: changelog - N/A

#988 Fix installs on Windows
  npm/install-wrangler.js
  npm/npm-shrinkwrap.json
  npm/package.json
  npm/uninstall-wrangler.js
Labels: changelog - N/A

#987 Add List Routes/Delete Route commands
  src/commands/mod.rs
  src/commands/publish/route.rs
  src/commands/route/mod.rs
  src/main.rs
  src/settings/toml/manifest.rs
  src/terminal/emoji.rs
Labels: changelog - N/A, priority - critical, status - needs review, subject - routes

#966 Alewis/deploy target
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/mod.rs
  src/commands/kv/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/main.rs
  src/settings/toml/deploy_target.rs
  src/settings/toml/environment.rs
  src/settings/toml/manifest.rs
  src/settings/toml/mod.rs
  src/settings/toml/route.rs
  src/settings/toml/target.rs
Labels: changelog - feature, priority - critical, status - needs review, subject - routes

#967 deploy target tests
  src/settings/toml/environment.rs
  src/settings/toml/manifest.rs
  src/settings/toml/site.rs
  src/settings/toml/tests/deploy_config.rs
  src/settings/toml/tests/mod.rs
  tests/fixture/wrangler_toml.rs
Labels: changelog - feature, priority - low, status - needs review, subject - routes

#1002 [dev] uses PR #28 of chrome-devtools-rs
  Cargo.lock
  Cargo.toml
  src/commands/dev/socket.rs
Labels: status - work in progress

#991 [dev] fix windows builds and timeouts
  Cargo.lock
  Cargo.toml
  src/commands/dev/mod.rs
  src/commands/dev/socket.rs
  src/commands/dev/socket/client.rs
  src/commands/dev/socket/mod.rs
Labels: changelog - N/A, status - needs review
