Repository cloudflare/wrangler-legacy, pull requests merged in 2020-08, with the labels that each got.

#1476 remove caching from tests for real
  .github/workflows/test.yml
Labels: changelog - maintenance, status - needs review

#1477 Added dev args to wrangler.toml
  src/main.rs
  src/settings/toml/dev.rs
  src/settings/toml/manifest.rs
  src/settings/toml/mod.rs
Labels: changelog - feature

#1492 Added wrangler login into auth errors
  src/commands/whoami.rs
  src/main.rs
  src/preview/upload.rs
  src/settings/global_user.rs
  src/upload/mod.rs
Labels: changelog - N/A

#1495 Change open_browser to open browser in child process
  src/terminal/browser.rs
Labels: changelog - fix

#1498 Have --host run dev unauthenticated
  src/commands/dev/mod.rs
  src/commands/dev/server_config/host.rs
  src/commands/dev/server_config/mod.rs
  src/commands/dev/server_config/protocol.rs
  src/main.rs
Labels: changelog - feature, subject - wrangler dev
