Repository cloudflare/wrangler-legacy, pull requests merged in 2020-06, with the labels that each got.

#1355 deprecate kv bucket attribute
  src/commands/kv/mod.rs
  src/commands/publish.rs
  src/settings/toml/kv_namespace.rs
  src/settings/toml/tests/mod.rs
  src/sites/mod.rs
Labels: changelog - maintenance, priority - critical, status - needs review, subject - site

#1339 Batched kv put and delete
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/kv/bulk.rs
  src/sites/upload.rs
Labels: changelog - fix, status - needs review

#1346 adds code of conduct
  CODE_OF_CONDUCT.md
Labels: changelog - maintenance, status - needs review

#1344 dont install wasm-pack for webpack type projects
  src/wranglerjs/mod.rs
Labels: changelog - fix

#1358 Pin dependency version for wasmpack and cargo-generate
  src/build/mod.rs
  src/commands/generate.rs
  src/install/dependencies.rs
  src/install/mod.rs
  src/watch/mod.rs
Labels: changelog - feature, status - needs review

#1361 adds email to code of conduct
  CODE_OF_CONDUCT.md
Labels: changelog - N/A, status - needs review

#1353 Feat/rename subdomain
  src/commands/kv/bulk/delete.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/namespace/delete.rs
  src/commands/secret.rs
  src/commands/subdomain.rs
  src/terminal/interactive.rs
Labels: changelog - feature, cross-team - API, priority - critical, status - needs review

#1371 Pretty print recieved json
  src/commands/dev/socket.rs
Labels: changelog - feature, status - needs review

#1387 Fix kv:namespace create --preview
  src/commands/kv/namespace/create.rs
Labels: changelog - N/A, status - needs review

#1391 use bulk api client directly in bulk action code
  src/commands/kv/bulk/mod.rs
  src/commands/kv/bulk/put.rs
  src/kv/bulk.rs
  src/sites/upload.rs
Labels: bug, priority - critical

#1392 increases default HTTP timeout to 1 min
  src/http/cf.rs
  src/http/legacy.rs
  src/http/mod.rs
Labels: changelog - fix, status - needs review

#1393 1.10.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release

#1396 initial stalebot configuration
  .github/stale.yml
Labels: changelog - maintenance, status - needs review

#1400 move batching into bulk module code
  src/commands/kv/bulk/delete.rs
  src/commands/kv/bulk/put.rs
  src/commands/publish.rs
  src/kv/bulk.rs
  src/main.rs
  src/preview/upload.rs
  src/sites/mod.rs
  src/sites/upload.rs
Labels: changelog - fix, priority - critical, status - needs review, subject - site

#1409 allow kv_namespaces in toml
  src/fixtures/wrangler_toml.rs
  src/settings/toml/environment.rs
Labels: changelog - fix, status - needs review

#1395 clarify location of account id in dashboard
  src/settings/toml/manifest.rs
Labels: changelog - fix, status - needs review

#1405 dev: listen on ipv4 by default
  src/commands/dev/gcs/server.rs
  src/commands/dev/server_config/mod.rs
Labels: changelog - feature, status - needs review

#1410 remove unused install::krate
  src/install/krate.rs
  src/install/mod.rs
Labels: changelog - maintenance, status - needs review

#1414 allow creation of preview namespace when namespace exists in toml
  src/commands/kv/namespace/create.rs
  src/kv/namespace/create.rs
  src/kv/namespace/upsert.rs
  src/settings/toml/manifest.rs
Labels: changelog - fix, status - needs review

#1413 [dev] allow multiple response header values
  src/commands/dev/gcs/headers.rs
Labels: changelog - fix, status - needs review

#1419 🐹 1.10.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release, status - needs review

#1423 Fix case of GitHub
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  npm/README.md
  src/main.rs
Labels: changelog - maintenance
