Repository cloudflare/wrangler-legacy, pull requests merged in 2020-02, with the labels that each got.

#1028 test rust with GitHub Actions
  .github/workflows/rust.yml
  azure-pipelines.yml
Labels: changelog - maintenance

#1009 Update cloudflare-rs, reqwest, http, uuid
  Cargo.lock
  Cargo.toml
  src/commands/kv/key/get.rs
  src/commands/kv/key/put.rs
  src/commands/preview/mod.rs
  src/commands/preview/upload.rs
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/subdomain/mod.rs
  src/http.rs
  src/install/krate.rs
Labels: changelog - maintenance, cross-team - cloudflare-rs, priority - critical

#1021 adds release checklist
  RELEASE_CHECKLIST.md
Labels: changelog - maintenance, status - needs review

#1000 Updates dependencies
  Cargo.lock
  src/commands/kv/mod.rs
  src/http.rs
Labels: changelog - maintenance

#1010 use static lifetimes
  tests/fixture/mod.rs
  tests/fixture/wrangler_toml.rs
Labels: category - refactor

#999 [dev] Live reload/code watching
  src/commands/dev/mod.rs
  src/commands/dev/socket.rs
  src/commands/dev/watch.rs
  src/main.rs
Labels: changelog - feature, status - needs review

#916 Feature: Multi-route support
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/upload.rs
  src/commands/kv/mod.rs
  src/commands/mod.rs
  src/commands/publish/mod.rs
  src/commands/publish/route.rs
  src/commands/route/mod.rs
  src/main.rs
  src/settings/toml/deploy_config.rs
  src/settings/toml/environment.rs
  src/settings/toml/manifest.rs
  src/settings/toml/mod.rs
  src/settings/toml/route.rs
  src/settings/toml/site.rs
  src/settings/toml/target.rs
  src/settings/toml/tests/deploy_config.rs
  src/settings/toml/tests/mod.rs
  src/terminal/emoji.rs
  tests/fixture/mod.rs
  tests/fixture/wrangler_toml.rs
Labels: changelog - feature, cross-team - API, cross-team - cloudflare-rs, feature branch, priority - critical, status - blocked, status - needs review, subject - routes

#883 [rc] [dev] Dev Server Feature Branch
  Cargo.lock
  Cargo.toml
  logs/connection.log
  src/commands/dev/headers.rs
  src/commands/dev/mod.rs
  src/commands/dev/server_config/host.rs
  src/commands/dev/server_config/listening_address.rs
  src/commands/dev/server_config/mod.rs
  src/commands/dev/socket.rs
  src/commands/dev/watch.rs
  src/commands/mod.rs
  src/commands/preview/mod.rs
  src/main.rs
  src/terminal/emoji.rs
Labels: feature branch, status - needs review, status - work in progress

#1043 fix route clap description
  src/main.rs
Labels: changelog - N/A

#1045 Add Secret commands
  Cargo.lock
  Cargo.toml
  src/commands/kv/bulk/delete.rs
  src/commands/kv/key/delete.rs
  src/commands/kv/mod.rs
  src/commands/kv/namespace/delete.rs
  src/commands/mod.rs
  src/commands/secret/mod.rs
  src/main.rs
  src/terminal/emoji.rs
  src/terminal/interactive.rs
  src/terminal/mod.rs
Labels: changelog - feature, cross-team - API, cross-team - cloudflare-rs, priority - critical, status - needs review, subject - secrets

#1014 Allow uploading of plain text bindings
  Cargo.lock
  Cargo.toml
  src/commands/kv/bucket/mod.rs
  src/commands/kv/mod.rs
  src/commands/publish/upload_form/mod.rs
  src/commands/publish/upload_form/plain_text.rs
  src/commands/publish/upload_form/project_assets.rs
  src/commands/publish/upload_form/wasm_module.rs
  src/settings/binding.rs
  src/settings/toml/environment.rs
  src/settings/toml/manifest.rs
  src/settings/toml/target.rs
  src/settings/toml/tests/mod.rs
  tests/fixture/mod.rs
  tests/fixture/wrangler_toml.rs
  tests/preview.rs
Labels: status - needs review

#1037 more github actinos
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/test.yml
  README.md
  azure-pipelines.yml
  ci/azure-create-tarball.yml
  ci/azure-install-node.yml
  ci/azure-install-rust.yml
Labels: changelog - maintenance

#1049 Adds alpha warning to wrangler dev
  Cargo.lock
  Cargo.toml
  src/commands/dev/mod.rs
  src/terminal/message_box.rs
  src/terminal/mod.rs
Labels: changelog - N/A, status - needs review

#1053 1.8.0-rc.0
  Cargo.lock
  Cargo.toml
  RELEASE_CHECKLIST.md
  npm/package.json
Labels: category - release

#1062 Correctly tar release binaries
  .github/workflows/release.yml
Labels: changelog - maintenance, status - needs review

#1065 s/text/vars/
  src/commands/kv/bucket/mod.rs
  src/commands/kv/mod.rs
  src/commands/publish/upload_form/mod.rs
  src/settings/toml/environment.rs
  src/settings/toml/manifest.rs
  src/settings/toml/target.rs
Labels: changelog - N/A, status - needs review, subject - secrets

#1063 Configure sourcemap file
  tests/build.rs
  wranglerjs/index.js
Labels: changelog - feature

#1069 ci: zip tars
  .github/workflows/release.yml
Labels: changelog - maintenance

#1074 don't inherit vars from top level
  src/settings/toml/manifest.rs
Labels: changelog - BREAKING, status - needs review

#1072 Fixes source map test failure
  tests/build.rs
Labels: changelog - maintenance, status - needs review

#1071 fixes clippy warnings
  src/commands/secret/mod.rs
  src/terminal/message_box.rs
  tests/build.rs
Labels: changelog - maintenance, status - needs review

#983 feat(whoami): return accounts and account ids on whoami
  Cargo.lock
  src/commands/whoami/mod.rs
Labels: changelog - feature

#1080 Fixes creation of release artifacts
  .github/workflows/release.yml
Labels: changelog - maintenance

#1075 refactor: extract upload and deploy to lib modules
  src/commands/build/wranglerjs/mod.rs
  src/commands/preview/upload.rs
  src/commands/publish.rs
  src/deploy/mod.rs
  src/deploy/route.rs
  src/lib.rs
  src/upload/form/mod.rs
  src/upload/form/plain_text.rs
  src/upload/form/project_assets.rs
  src/upload/form/text_blob.rs
  src/upload/form/wasm_module.rs
  src/upload/krate.rs
  src/upload/mod.rs
  src/upload/package.rs
Labels: category - refactor, priority - low, status - needs review

#1090 Run CI on pull requests not pushes
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: changelog - maintenance, status - needs review

#1086 Display status code in wrangler dev request output
  src/commands/dev/mod.rs
Labels: status - needs cargo fmt

#1087 Upload "draft" worker if secret is created before initial worker script has been uploaded
  src/commands/secret/mod.rs
Labels: category - feature, priority - critical, status - needs review, subject - secrets

#1099 Add instructions for releasing release candidates
  RELEASE_CHECKLIST.md
  src/commands/dev/edge/headers.rs
  src/commands/dev/edge/server.rs
  src/commands/dev/edge/setup.rs
Labels: changelog - maintenance, status - needs review

#1050 Adds tests to config vars PR
  tests/fixture/wrangler_toml.rs
  tests/preview.rs
Labels: changelog - N/A, status - needs rebase
