Repository cloudflare/wrangler-legacy, pull requests merged in 2020-03, with the labels that each got.

#1112 Ensure trailing whitespace added in commandline user input is stripped.
  src/main.rs
  src/terminal/interactive.rs
Labels: category - maintenance, priority - critical, status - needs review, subject - secrets

#1117 [dev] fix: properly route to new preview id after reload
  src/commands/dev/mod.rs
Labels: changelog - fix, status - needs review

#1114 [dev] Improves error message when there is no internet connection
  src/commands/dev/mod.rs
Labels: changelog - feature, status - needs review

#1116 😈 1.8.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/package.json
  src/main.rs
Labels: changelog - maintenance, status - blocked

#1128 unifies attention grabbing messages
  Cargo.lock
  Cargo.toml
  src/commands/dev/mod.rs
  src/commands/preview/upload.rs
  src/main.rs
  src/terminal/message.rs
  src/terminal/message_box.rs
  src/terminal/mod.rs
Labels: changelog - maintenance, status - needs review

#1103 Readme: needs internet to build locally (-dev)
  npm/README.md
Labels: category - docs, priority - nice to have

#1130 moves from boxx to billboard
  Cargo.lock
  Cargo.toml
  src/terminal/message.rs
Labels: changelog - N/A, status - needs review

#1115 Delay KV bulk delete
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/kv/bucket/upload.rs
  src/commands/preview/upload.rs
  src/commands/publish.rs
  src/commands/secret/mod.rs
  src/http.rs
  src/terminal/message.rs
  src/upload/mod.rs
Labels: changelog - fix, priority - critical, status - needs review, subject - site

#1018 feat: configurable binary host url
  README.md
  npm/binary.js
Labels: changelog - feature, status - needs review

#1145 Asset Manifest QOL improvements
  src/commands/kv/bucket/mod.rs
  src/commands/kv/bucket/sync.rs
  src/commands/preview/upload.rs
  src/commands/publish.rs
Labels: changelog - maintenance, status - needs review

#1148 removes clippy warnings
  src/commands/kv/bucket/mod.rs
  src/commands/publish.rs
  src/commands/secret/mod.rs
  src/commands/whoami/mod.rs
  src/settings/toml/tests/deploy_config.rs
  tests/fixture/wrangler_toml.rs
  tests/preview.rs
Labels: changelog - maintenance

#1154 add EITHER to config error message
  src/settings/toml/deploy_config.rs
Labels: changelog - maintenance, status - needs review

#1149 tidy tail file, unescape json log output
  src/commands/tail/mod.rs
Labels: priority - critical, status - needs review, subject - logging

#1144 removes unused logs folder
  logs/connection.log
Labels: changelog - N/A, status - needs review

#1164 fix: re-order wrangler config warning arguments
  src/main.rs
Labels: changelog - fix, status - needs review

#1166 fix: remove unused README badges
  README.md
Labels: changelog - maintenance, status - needs review

#1165 🍟 1.8.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/README.md
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release, status - needs review

#1131 Prototype: Wrangler Tail
  Cargo.lock
  Cargo.toml
  src/commands/mod.rs
  src/commands/tail/mod.rs
  src/http.rs
  src/install/mod.rs
  src/main.rs
Labels: category - feature, priority - nice to have, status - needs review, subject - logging

#1171 fix: allow multiline files to be piped to wrangler secret
  Cargo.toml
  src/commands/secret/mod.rs
  src/terminal/interactive.rs
Labels: changelog - fix, status - needs review

#1181 temp: dont uninstall to keep wrangler config around
  npm/package.json
Labels: changelog - fix

#1183 🎭 1.8.4
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  npm/npm-shrinkwrap.json
  npm/package.json
Labels: category - release
